name: 🐛 Bug report
description: Report a bug to help us improve
body:
- type: markdown
  attributes:
    value: |
      Thank you for submitting a bug report!

      Please fill out the template below to make it easier to debug your problem.

       If you are not sure if it is a bug or not, you can contact us via the available [support channels](https://github.com/Ironchip-Security/bug-tracker/issues/new/choose).
- type: checkboxes
  attributes:
    label: Preflight Checklist
    description: Please ensure you've completed all of the following.
    options:
      - label: I have searched the [issue tracker](https://github.com/Ironchip-Security/bug-tracker/issues) for an issue that matches the one I want to file, without success.
        required: true
      - label: I am not looking for support or already pursued the available [support channels](https://helpcenter.ironchip.com/support/) without success.
        required: true
- type: input
  attributes:
    label: Version
    description: What version are you running? You can see the version going to the top right of the application, click on the 3 dots, and then click on app information. 
    placeholder: 1.1.2
  validations:
    required: true
- type: dropdown
  attributes:
    label: Device Type
    description: Which Devide type are you using?
    options:
      - IOs
      - Android
      - Windows
      - Linux
      - MacOS
  validations:
    required: true
- type: dropdown
  attributes:
    label: Installation Type
    description: How did you install?
    options:
      - Nexus 
      - Official Store
      - Other
    multiple: true
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual Behavior
    description: A clear description of what actually happens.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior if it is not self-explanatory.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
- type: textarea
  attributes:
    label: Additional Information
    description: Links? References? Anything that will give us more context about the issue that you are encountering!
- type: textarea
  attributes:
    label: Logs
    description: application logs (if relevant).
    render: shell

